# roles/common/tasks/maintenance.yml
---
- name: Install Python-apt
# This may be deleted as we placed it into the packer build file on  08.03.2021
  become: true
  apt: 
    name: python3-apt

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: 'yes'
    update_cache: 'yes'
    cache_valid_time: 86400 #One day

- name: Check if "/var/run/reboot-required" exists
  become: true
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the VM if required
  become: true
  reboot:
  when: reboot_required.stat.exists
