name: Terraform-Plan-App

on:
  workflow_dispatch:

env:
  TERRAFORM_VERSION: '1.6.0'
  TERRAFORM_WORKING_DIRECTORY: "./src/terraform/app"
  APPLICATION_NAME: "tfany-app"
  ENVIRONMENT_NAME: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: setup
      name: Setup `terraform`
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false

    - id: terraform
      name: Terraform Plan
      env:
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        TF_VAR_application_name: ${{ env.APPLICATION_NAME }}
        TF_VAR_environment_name: ${{ env.ENVIRONMENT_NAME }}
      working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ vars.BACKEND_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ vars.BACKEND_STORAGE_CONTAINER_NAME }}" \
          -backend-config="key=${{ env.APPLICATION_NAME }}-${{ env.ENVIRONMENT_NAME }}"

        terraform plan
